# Generated by Django 5.2.17 on 2026-08-29 15:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_interaction_phone_number_lead_contacted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('call_outbound_per_minute', 'Outbound call — per minute'), ('call_inbound_per_minute', 'Inbound call — per minute'), ('sms_per_segment', 'SMS — per segment'), ('number_monthly_rental', 'Phone number — monthly rental'), ('number_sms_capability_fee', 'Phone number — SMS capability add-on (monthly)'), ('ten_dlc_campaign_fee', '10DLC campaign fee (monthly)'), ('lead_search_per_query', 'Prospector web search — per query')], max_length=64, unique=True)),
                ('cost_usd', models.DecimalField(decimal_places=4, max_digits=8)),
                ('unit', models.CharField(default='per minute', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='TenantWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_usd', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('low_balance_threshold_usd', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('low_balance_notified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fx_rate_used', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pkr_base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gateway_fee_pkr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_charged_pkr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('net_credited_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gateway_order_id', models.CharField(max_length=128, unique=True)),
                ('gateway_reference', models.CharField(blank=True, max_length=128)),
                ('qr_payload', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='wallet_invoices/')),
                ('expires_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_topups', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TOPUP', 'Top-up'), ('USAGE_CALL', 'Call'), ('USAGE_SMS', 'SMS'), ('USAGE_LEAD_SEARCH', 'Lead search'), ('USAGE_NUMBER_RENTAL', 'Number rental'), ('USAGE_OTHER', 'Other'), ('ADJUSTMENT', 'Manual adjustment')], max_length=24)),
                ('amount_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('balance_after_usd', models.DecimalField(decimal_places=4, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.interaction')),
                ('related_phone_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phonenumber')),
                ('related_scrape_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.scrapetask')),
                ('related_topup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='wallet.wallettopup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'type', 'created_at'], name='wallet_wall_tenant__a13bc3_idx')],
            },
        ),
    ]
