# Generated by Django 5.2.17 on 2026-08-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_manualcredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrate',
            name='key',
            field=models.CharField(choices=[('call_outbound_per_minute', 'Outbound call — per minute'), ('call_inbound_per_minute', 'Inbound call — per minute'), ('sms_per_segment', 'SMS — per segment (legacy, unused)'), ('sms_outbound_per_segment', 'Outbound SMS — per segment'), ('sms_inbound_per_segment', 'Inbound SMS — per segment'), ('number_monthly_rental', 'Phone number — monthly rental'), ('number_sms_capability_fee', 'Phone number — SMS capability add-on (monthly)'), ('lead_search_per_query', 'Prospector web search — per search (flat, up to 25 leads)'), ('lead_verification_per_row', 'Bulk upload — per-row verification')], max_length=64, unique=True),
        ),
    ]
