# Generated by Django 5.2.17 on 2026-09-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_pricingrate_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrate',
            name='key',
            field=models.CharField(choices=[('call_outbound_per_minute', 'Outbound call — per minute'), ('call_inbound_per_minute', 'Inbound call — per minute'), ('sms_outbound_per_segment', 'Outbound SMS — per segment'), ('sms_inbound_per_segment', 'Inbound SMS — per segment'), ('number_monthly_rental', 'Phone number — monthly rental'), ('number_sms_capability_fee', 'Phone number — SMS capability add-on (monthly)'), ('lead_search_per_query', 'Prospector web search — per search (flat, up to 25 leads)'), ('lead_verification_per_row', 'Bulk upload — per-row verification'), ('platform_fee_monthly', 'Platform fee — monthly recurring')], max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('TOPUP', 'Top-up'), ('USAGE_CALL', 'Call'), ('USAGE_SMS', 'SMS'), ('USAGE_LEAD_SEARCH', 'Lead search'), ('USAGE_LEAD_VERIFICATION', 'Lead verification'), ('USAGE_NUMBER_RENTAL', 'Number rental'), ('USAGE_PLATFORM_FEE', 'Platform fee'), ('USAGE_OTHER', 'Other'), ('ADJUSTMENT', 'Manual adjustment')], max_length=24),
        ),
    ]
