# Generated by Django 5.2.17 on 2026-09-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_unique_billing_per_source'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallettransaction',
            name='unique_wallettransaction_per_interaction',
        ),
        migrations.RemoveConstraint(
            model_name='wallettransaction',
            name='unique_wallettransaction_per_scrape_task',
        ),
    ]
