# Generated by Django 5.2.17 on 2026-08-29 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_leaduploadtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='core.phonenumber'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contacted_at',
            field=models.DateTimeField(blank=True, help_text="Set the moment someone clicks 'Contact' in the Leads List (or logs a call/text directly). This is the ONLY thing that makes a lead appear in the CRM/Dialer tab — the tab stays empty until then.", null=True),
        ),
        migrations.AddField(
            model_name='leaduploadtask',
            name='failed_rows',
            field=models.JSONField(blank=True, default=list, help_text='List of {row, label, reason} dicts for rows rejected during verification.'),
        ),
        migrations.AddField(
            model_name='scrapetask',
            name='existing_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapetask',
            name='freshly_scraped_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapetask',
            name='master_pulled_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MasterLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('keywords', models.CharField(blank=True, help_text='Space-separated search terms this lead matches — powers waterfall lookups.', max_length=500)),
                ('do_not_contact', models.BooleanField(default=False, help_text="Global opt-out — propagated the instant ANY tenant's copy of this contact texts STOP.")),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_tenant', models.ForeignKey(blank=True, help_text='Tenant whose scrape/upload first verified this lead. Informational only — grants no special access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-verified_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='unique_master_email_when_present'), models.UniqueConstraint(condition=models.Q(('phone_number', ''), _negated=True), fields=('phone_number',), name='unique_master_phone_when_present')],
            },
        ),
    ]
