# Generated by Django 5.2.17 on 2026-08-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_interaction_missed'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional proof — e.g. a bank/SadaPay transfer screenshot.', null=True, upload_to='support_attachments/'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
