# Generated by Django 5.2.17 on 2026-09-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_supportmessage_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='next_platform_fee_charge_at',
            field=models.DateTimeField(blank=True, help_text='When the next recurring platform fee should be deducted. Rolls forward 30 days from whichever date it was last successfully charged (not a fixed calendar day) — a late payment shifts every future due date by the same delay.', null=True),
        ),
    ]
