# Generated by Django 5.2.17 on 2026-09-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tenant_next_platform_fee_charge_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='last_billed_at',
            field=models.DateField(blank=True, help_text="First day of the calendar month this number's rental was last charged through. Set at purchase and advanced by the monthly sweep — prevents double-charging or skipping a month.", null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='telnyx_phone_number_id',
            field=models.CharField(blank=True, help_text="Telnyx's actual phone_number resource ID (not the order ID) — required to release/deactivate the number via the Telnyx API.", max_length=128),
        ),
    ]
