# Generated by Django 5.2.17 on 2026-09-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customuser_unique_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
